[llm]
#model = "gemma3"
#model = "qwen3:4b"
#model = "claude-3.5-sonnet-v2"
#model = "llama3-2-90b-instruct-v1:0"

# ollama
#base_url = "http://localhost:11434/v1/chat/completions"

# yi api
model = "gpt-4o-mini"
api_key = "sk-wuTITomWJ5hVYsVb304d3f94Ec144e3bAa5eCc11Ff6aA0E9"
base_url = "https://vip.apiyi.com/v1/chat/completions"


# Alibaba
#model = "qwen-plus"
#api_key = "sk-da4935959a9b46c88a60d8c3f416d334"
#base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"


max_tokens = 8192
#max_tokens = 4096
temperature = 0.8

[chunking]
chunk_size = 100  # Number of words per chunk
overlap = 20      # Number of words to overlap between chunks

[standardization]
enabled = true               # Whether to enable entity standardization
use_llm_for_entities = true  # Whether to use LLM for additional entity resolution

[inference]
enabled = true             # Whether to enable relationship inference
use_llm_for_inference = true  # Whether to use LLM for relationship inference
apply_transitive = true    # Whether to apply transitive inference rules

[visualization]
edge_smooth = false # Options: false, "dynamic", "continuous", "discrete", "diagonalCross", 
                    # "straightCross", "horizontal", "vertical", "curvedCW", "curvedCCW", "cubicBezier": true = "continuous"
