[llm]
#model = "Qwen3-4B-Thinking"  # ubuntu model server
model = "Qwen3-4B-Instruct-2507" # ubuntu model server
#model = "gemma3"model = "qwen3:4b" # hw 21 ollama model
# other model
#model = "gpt4o"
#model = "claude-3.5-sonnet-v2"
#model = "llama3-2-90b-instruct-v1:0"



api_key = "sk-1234"
#base_url = "http://localhost:11434/v1/chat/completions"
#base_url = "http://10.30.30.97:11434/v1/chat/completions"  # hw ollama
#base_url = "http://localhost:4000/v1/chat/completions"
base_url = "http://192.168.1.6:8001/v1/chat/completions" # # ubuntu lf llm server

max_tokens = 300000
#max_tokens = 4096
temperature = 0.8

[chunking]
chunk_size = 100  # Number of words per chunk
overlap = 20      # Number of words to overlap between chunks

[standardization]
enabled = true               # Whether to enable entity standardization
use_llm_for_entities = true  # Whether to use LLM for additional entity resolution

[inference]
enabled = true             # Whether to enable relationship inference
use_llm_for_inference = true  # Whether to use LLM for relationship inference
apply_transitive = true    # Whether to apply transitive inference rules

[visualization]
edge_smooth = false # Options: false, "dynamic", "continuous", "discrete", "diagonalCross", 
                    # "straightCross", "horizontal", "vertical", "curvedCW", "curvedCCW", "cubicBezier": true = "continuous"



[neo4j]  
enabled = true  
uri = "bolt://localhost:7687"
username = "neo4j"  
password = "aa1230.aa2"
